name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 3: Build the Docker image using Dockerfile.dev
      - name: Build Docker image
        run: |
          docker build -f Dockerfile.dev -t my-react-app .

      # Step 4: Run tests inside the Docker container
      - name: Run tests
        run: |
          docker run --rm my-react-app npm run test -- --watchAll=false
